# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/amin/Documents/ap/Project/phase2

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/amin/Documents/ap/Project/phase2

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/amin/Documents/ap/Project/phase2/CMakeFiles /home/amin/Documents/ap/Project/phase2/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/amin/Documents/ap/Project/phase2/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named chess

# Build rule for target.
chess: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 chess
.PHONY : chess

# fast build rule for target.
chess/fast:
	$(MAKE) -f CMakeFiles/chess.dir/build.make CMakeFiles/chess.dir/build
.PHONY : chess/fast

src/bishop.o: src/bishop.cpp.o

.PHONY : src/bishop.o

# target to build an object file
src/bishop.cpp.o:
	$(MAKE) -f CMakeFiles/chess.dir/build.make CMakeFiles/chess.dir/src/bishop.cpp.o
.PHONY : src/bishop.cpp.o

src/bishop.i: src/bishop.cpp.i

.PHONY : src/bishop.i

# target to preprocess a source file
src/bishop.cpp.i:
	$(MAKE) -f CMakeFiles/chess.dir/build.make CMakeFiles/chess.dir/src/bishop.cpp.i
.PHONY : src/bishop.cpp.i

src/bishop.s: src/bishop.cpp.s

.PHONY : src/bishop.s

# target to generate assembly for a file
src/bishop.cpp.s:
	$(MAKE) -f CMakeFiles/chess.dir/build.make CMakeFiles/chess.dir/src/bishop.cpp.s
.PHONY : src/bishop.cpp.s

src/board.o: src/board.cpp.o

.PHONY : src/board.o

# target to build an object file
src/board.cpp.o:
	$(MAKE) -f CMakeFiles/chess.dir/build.make CMakeFiles/chess.dir/src/board.cpp.o
.PHONY : src/board.cpp.o

src/board.i: src/board.cpp.i

.PHONY : src/board.i

# target to preprocess a source file
src/board.cpp.i:
	$(MAKE) -f CMakeFiles/chess.dir/build.make CMakeFiles/chess.dir/src/board.cpp.i
.PHONY : src/board.cpp.i

src/board.s: src/board.cpp.s

.PHONY : src/board.s

# target to generate assembly for a file
src/board.cpp.s:
	$(MAKE) -f CMakeFiles/chess.dir/build.make CMakeFiles/chess.dir/src/board.cpp.s
.PHONY : src/board.cpp.s

src/king.o: src/king.cpp.o

.PHONY : src/king.o

# target to build an object file
src/king.cpp.o:
	$(MAKE) -f CMakeFiles/chess.dir/build.make CMakeFiles/chess.dir/src/king.cpp.o
.PHONY : src/king.cpp.o

src/king.i: src/king.cpp.i

.PHONY : src/king.i

# target to preprocess a source file
src/king.cpp.i:
	$(MAKE) -f CMakeFiles/chess.dir/build.make CMakeFiles/chess.dir/src/king.cpp.i
.PHONY : src/king.cpp.i

src/king.s: src/king.cpp.s

.PHONY : src/king.s

# target to generate assembly for a file
src/king.cpp.s:
	$(MAKE) -f CMakeFiles/chess.dir/build.make CMakeFiles/chess.dir/src/king.cpp.s
.PHONY : src/king.cpp.s

src/knight.o: src/knight.cpp.o

.PHONY : src/knight.o

# target to build an object file
src/knight.cpp.o:
	$(MAKE) -f CMakeFiles/chess.dir/build.make CMakeFiles/chess.dir/src/knight.cpp.o
.PHONY : src/knight.cpp.o

src/knight.i: src/knight.cpp.i

.PHONY : src/knight.i

# target to preprocess a source file
src/knight.cpp.i:
	$(MAKE) -f CMakeFiles/chess.dir/build.make CMakeFiles/chess.dir/src/knight.cpp.i
.PHONY : src/knight.cpp.i

src/knight.s: src/knight.cpp.s

.PHONY : src/knight.s

# target to generate assembly for a file
src/knight.cpp.s:
	$(MAKE) -f CMakeFiles/chess.dir/build.make CMakeFiles/chess.dir/src/knight.cpp.s
.PHONY : src/knight.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/chess.dir/build.make CMakeFiles/chess.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/chess.dir/build.make CMakeFiles/chess.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/chess.dir/build.make CMakeFiles/chess.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/null.o: src/null.cpp.o

.PHONY : src/null.o

# target to build an object file
src/null.cpp.o:
	$(MAKE) -f CMakeFiles/chess.dir/build.make CMakeFiles/chess.dir/src/null.cpp.o
.PHONY : src/null.cpp.o

src/null.i: src/null.cpp.i

.PHONY : src/null.i

# target to preprocess a source file
src/null.cpp.i:
	$(MAKE) -f CMakeFiles/chess.dir/build.make CMakeFiles/chess.dir/src/null.cpp.i
.PHONY : src/null.cpp.i

src/null.s: src/null.cpp.s

.PHONY : src/null.s

# target to generate assembly for a file
src/null.cpp.s:
	$(MAKE) -f CMakeFiles/chess.dir/build.make CMakeFiles/chess.dir/src/null.cpp.s
.PHONY : src/null.cpp.s

src/pawn.o: src/pawn.cpp.o

.PHONY : src/pawn.o

# target to build an object file
src/pawn.cpp.o:
	$(MAKE) -f CMakeFiles/chess.dir/build.make CMakeFiles/chess.dir/src/pawn.cpp.o
.PHONY : src/pawn.cpp.o

src/pawn.i: src/pawn.cpp.i

.PHONY : src/pawn.i

# target to preprocess a source file
src/pawn.cpp.i:
	$(MAKE) -f CMakeFiles/chess.dir/build.make CMakeFiles/chess.dir/src/pawn.cpp.i
.PHONY : src/pawn.cpp.i

src/pawn.s: src/pawn.cpp.s

.PHONY : src/pawn.s

# target to generate assembly for a file
src/pawn.cpp.s:
	$(MAKE) -f CMakeFiles/chess.dir/build.make CMakeFiles/chess.dir/src/pawn.cpp.s
.PHONY : src/pawn.cpp.s

src/piece.o: src/piece.cpp.o

.PHONY : src/piece.o

# target to build an object file
src/piece.cpp.o:
	$(MAKE) -f CMakeFiles/chess.dir/build.make CMakeFiles/chess.dir/src/piece.cpp.o
.PHONY : src/piece.cpp.o

src/piece.i: src/piece.cpp.i

.PHONY : src/piece.i

# target to preprocess a source file
src/piece.cpp.i:
	$(MAKE) -f CMakeFiles/chess.dir/build.make CMakeFiles/chess.dir/src/piece.cpp.i
.PHONY : src/piece.cpp.i

src/piece.s: src/piece.cpp.s

.PHONY : src/piece.s

# target to generate assembly for a file
src/piece.cpp.s:
	$(MAKE) -f CMakeFiles/chess.dir/build.make CMakeFiles/chess.dir/src/piece.cpp.s
.PHONY : src/piece.cpp.s

src/queen.o: src/queen.cpp.o

.PHONY : src/queen.o

# target to build an object file
src/queen.cpp.o:
	$(MAKE) -f CMakeFiles/chess.dir/build.make CMakeFiles/chess.dir/src/queen.cpp.o
.PHONY : src/queen.cpp.o

src/queen.i: src/queen.cpp.i

.PHONY : src/queen.i

# target to preprocess a source file
src/queen.cpp.i:
	$(MAKE) -f CMakeFiles/chess.dir/build.make CMakeFiles/chess.dir/src/queen.cpp.i
.PHONY : src/queen.cpp.i

src/queen.s: src/queen.cpp.s

.PHONY : src/queen.s

# target to generate assembly for a file
src/queen.cpp.s:
	$(MAKE) -f CMakeFiles/chess.dir/build.make CMakeFiles/chess.dir/src/queen.cpp.s
.PHONY : src/queen.cpp.s

src/rook.o: src/rook.cpp.o

.PHONY : src/rook.o

# target to build an object file
src/rook.cpp.o:
	$(MAKE) -f CMakeFiles/chess.dir/build.make CMakeFiles/chess.dir/src/rook.cpp.o
.PHONY : src/rook.cpp.o

src/rook.i: src/rook.cpp.i

.PHONY : src/rook.i

# target to preprocess a source file
src/rook.cpp.i:
	$(MAKE) -f CMakeFiles/chess.dir/build.make CMakeFiles/chess.dir/src/rook.cpp.i
.PHONY : src/rook.cpp.i

src/rook.s: src/rook.cpp.s

.PHONY : src/rook.s

# target to generate assembly for a file
src/rook.cpp.s:
	$(MAKE) -f CMakeFiles/chess.dir/build.make CMakeFiles/chess.dir/src/rook.cpp.s
.PHONY : src/rook.cpp.s

src/templates.o: src/templates.cpp.o

.PHONY : src/templates.o

# target to build an object file
src/templates.cpp.o:
	$(MAKE) -f CMakeFiles/chess.dir/build.make CMakeFiles/chess.dir/src/templates.cpp.o
.PHONY : src/templates.cpp.o

src/templates.i: src/templates.cpp.i

.PHONY : src/templates.i

# target to preprocess a source file
src/templates.cpp.i:
	$(MAKE) -f CMakeFiles/chess.dir/build.make CMakeFiles/chess.dir/src/templates.cpp.i
.PHONY : src/templates.cpp.i

src/templates.s: src/templates.cpp.s

.PHONY : src/templates.s

# target to generate assembly for a file
src/templates.cpp.s:
	$(MAKE) -f CMakeFiles/chess.dir/build.make CMakeFiles/chess.dir/src/templates.cpp.s
.PHONY : src/templates.cpp.s

src/translate.o: src/translate.cpp.o

.PHONY : src/translate.o

# target to build an object file
src/translate.cpp.o:
	$(MAKE) -f CMakeFiles/chess.dir/build.make CMakeFiles/chess.dir/src/translate.cpp.o
.PHONY : src/translate.cpp.o

src/translate.i: src/translate.cpp.i

.PHONY : src/translate.i

# target to preprocess a source file
src/translate.cpp.i:
	$(MAKE) -f CMakeFiles/chess.dir/build.make CMakeFiles/chess.dir/src/translate.cpp.i
.PHONY : src/translate.cpp.i

src/translate.s: src/translate.cpp.s

.PHONY : src/translate.s

# target to generate assembly for a file
src/translate.cpp.s:
	$(MAKE) -f CMakeFiles/chess.dir/build.make CMakeFiles/chess.dir/src/translate.cpp.s
.PHONY : src/translate.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... chess"
	@echo "... src/bishop.o"
	@echo "... src/bishop.i"
	@echo "... src/bishop.s"
	@echo "... src/board.o"
	@echo "... src/board.i"
	@echo "... src/board.s"
	@echo "... src/king.o"
	@echo "... src/king.i"
	@echo "... src/king.s"
	@echo "... src/knight.o"
	@echo "... src/knight.i"
	@echo "... src/knight.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/null.o"
	@echo "... src/null.i"
	@echo "... src/null.s"
	@echo "... src/pawn.o"
	@echo "... src/pawn.i"
	@echo "... src/pawn.s"
	@echo "... src/piece.o"
	@echo "... src/piece.i"
	@echo "... src/piece.s"
	@echo "... src/queen.o"
	@echo "... src/queen.i"
	@echo "... src/queen.s"
	@echo "... src/rook.o"
	@echo "... src/rook.i"
	@echo "... src/rook.s"
	@echo "... src/templates.o"
	@echo "... src/templates.i"
	@echo "... src/templates.s"
	@echo "... src/translate.o"
	@echo "... src/translate.i"
	@echo "... src/translate.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

